name: ‚ú® Check Conventional Commit Title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened

permissions:
  pull-requests: write

jobs:
  lint-title:
    runs-on: ubuntu-latest
    steps:
      - name: üëÄ Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        id: lint_pr_title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            build
            chore
            ci
            docs
            feat
            fix
            perf
            refactor
            revert
            style
            test

      - name: ‚ùå Add a lint comment
        uses: actions/github-script@v7
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        env:
          ACTOR: ${{ github.actor }}
          ERROR_MESSAGE: ${{ steps.lint_pr_title.outputs.error_message }}
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
            const lintTitleComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('# ‚ùå Pull Request Title Linting Failed')
            })
            const body = `# ‚ùå Pull Request Title Linting Failed

            @$ACTOR, thank you for opening this pull request üëãüèº

            We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted.

            Details:

            \`\`\`
            ${process.env.ERROR_MESSAGE}
            \`\`\`

            Please update the title of this pull request to follow the specification.
            <!-- generated-comment [Title-Lint]($WORKFLOW_REF) -->`

            if (!lintTitleComment) {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: body
              })
            }

      - name: ‚úÖ Add a Fixed comment
        uses: actions/github-script@v7
        if: ${{ steps.lint_pr_title.outputs.error_message == null }}
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
            const lintTitleComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('# ‚ùå Pull Request Title Linting Failed')
            })
            const body = `# ‚úÖ Pull Request Title Linting Passed

            Thank you for updating the title of this pull request to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/).

            <!-- generated-comment [Title-Lint]($WORKFLOW_REF) -->`

            if (lintTitleComment) {
              await github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: lintTitleComment.id,
              })
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: body
              })
            }
